=== CenturyLinkCloud/mdw/mdw-schemas/schemas/Task/TaskView_v03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
  xmlns="http://mdw.centurylink.com/task" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  attributeFormDefault="unqualified"
  targetNamespace="http://mdw.centurylink.com/task">

  <xsd:element name="view">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="list" type="UiList" />
          <xsd:element name="filter" type="UiFilter" />
          <xsd:element name="detail" type="UiDetail" />
          <xsd:element name="chart" type="UiChart" />
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="skin" type="xsd:string" use="optional" />
      <xsd:attribute name="showCommonGroup" type="xsd:boolean" use="optional" default="true" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="UiList">
    <xsd:sequence>
      <xsd:element name="column" type="UiColumn"  maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" use="required" />
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="model" type="xsd:string" use="required" />
    <xsd:attribute name="columnMapper" type="xsd:string" use="optional" />
    <xsd:attribute name="controller" type="xsd:string" use="optional" />
    <xsd:attribute name="filter" type="xsd:string" use="optional" />
    <xsd:attribute name="defaultSortColumn" type="xsd:string" use="optional" />
    <xsd:attribute name="defaultSortDescending" type="xsd:boolean" use="optional" />
    <xsd:attribute name="paginatedResponse" type="xsd:boolean" use="optional" default="false" />
    <xsd:attribute name="displayRows" type="xsd:positiveInteger" use="optional" default="20" />
    <xsd:attribute name="allRowsLink" type="xsd:boolean" use="optional" default="false" />
    <xsd:attribute name="exportable" type="xsd:boolean" use="optional" default="true" />
    <xsd:attribute name="showTimings" type="xsd:boolean" use="optional" default="false" />
    <xsd:attribute name="ajaxEnabled" type="xsd:boolean" use="optional" default="false" />
    <xsd:attribute name="customButtons" type="xsd:string" use="optional" />
    <xsd:attribute name="groupingOptions" type="xsd:string" use="optional" />
    <xsd:attribute name="defaultGroupBy" type="xsd:string" use="optional" />
    <xsd:attribute name="pageSizeOptions" type="xsd:string" use="optional" />
    <xsd:attribute name="columnarFilters" type="xsd:boolean" use="optional" default="false" />
    <xsd:attribute name="searchable" type="xsd:boolean" use="optional" default="false" />
    <xsd:attribute name="showAllDisplayRows" type="xsd:positiveInteger" use="optional" default="200"/>    
  </xsd:complexType>

  <xsd:complexType name="UiColumn">
    <xsd:attribute name="attribute" type="xsd:string" use="required" />
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="checkbox" type="xsd:boolean" use="optional" default="false" />    
    <xsd:attribute name="decoder" type="xsd:string" use="optional" />
    <xsd:attribute name="linkAction" type="xsd:string" use="optional" />
    <xsd:attribute name="linkScript" type="xsd:string" use="optional" />
    <xsd:attribute name="linkCondition" type="xsd:string" use="optional" />
    <xsd:attribute name="linkTarget" type="xsd:string" use="optional" />
    <xsd:attribute name="rolesAllowedToView" type="xsd:string" use="optional" />
    <xsd:attribute name="dateFormat" type="xsd:string" use="optional" />
    <xsd:attribute name="styleClass" type="xsd:string" use="optional" />
    <xsd:attribute name="styleCondition" type="xsd:string" use="optional" />
    <xsd:attribute name="expandable" type="xsd:boolean" use="optional" default="false" />
    <xsd:attribute name="expandedContent" type="xsd:string" use="optional" />
    <xsd:attribute name="sortable" type="xsd:boolean" use="optional" default="false" />
    <xsd:attribute name="image" type="xsd:string" use="optional" />
    <xsd:attribute name="display" type="xsd:boolean" use="optional" default="true" />
    <xsd:attribute name="filterField" type="xsd:string" use="optional" />
    <xsd:attribute name="onclick" type="xsd:string" use="optional" />
    <!-- deprecated -->
    <xsd:attribute name="expandAttribute" type="xsd:string" use="optional" />
    <xsd:attribute name="dbColumn" type="xsd:string" use="optional" />
  </xsd:complexType>
  
  <xsd:complexType name="UiFilter">
    <xsd:sequence>
      <xsd:element name="field" type="UiField"  maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" use="required" />
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="model" type="xsd:string" use="required" />
    <xsd:attribute name="width" type="xsd:string" use="optional" />
  </xsd:complexType>

  <xsd:complexType name="UiField">
    <xsd:attribute name="attribute" type="xsd:string" use="required" />
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="checkbox" type="xsd:boolean" use="optional" default="false" />
    <xsd:attribute name="modelAttribute" type="xsd:string" use="optional" />
    <xsd:attribute name="modelType" type="xsd:string" use="optional" />
    <xsd:attribute name="type" type="UiInputType" use="required" />
    <xsd:attribute name="list" type="xsd:string" use="optional" />
    <xsd:attribute name="lister" type="xsd:string" use="optional" />
    <xsd:attribute name="defaultValue" type="xsd:string" use="optional" />
    <xsd:attribute name="firstItemLabel" type="xsd:string" use="optional" />
    <xsd:attribute name="expandable" type="xsd:boolean" use="optional" />
  </xsd:complexType>

  <xsd:simpleType name="UiInputType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="textInput"/>
      <xsd:enumeration value="digitInput"/>
      <xsd:enumeration value="selectInput"/>
      <xsd:enumeration value="dateInput"/>
      <xsd:enumeration value="dateRange"/>      
      <xsd:enumeration value="tnInput"/>
      <xsd:enumeration value="multiSelectInput"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="UiDetail">
    <xsd:sequence>
      <xsd:element name="row" type="UiRow"  maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" use="required" />
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="model" type="xsd:string" use="required" />
    <xsd:attribute name="controller" type="xsd:string" use="optional" />
    <xsd:attribute name="labelWidth" type="xsd:string" use="optional" />
    <xsd:attribute name="valueWidth" type="xsd:string" use="optional" />
    <xsd:attribute name="layoutColumns" type="xsd:positiveInteger" use="optional" />
    <xsd:attribute name="rolesAllowedToEdit" type="xsd:string" use="optional" />
  </xsd:complexType>

  <xsd:complexType name="UiRow"> 
    <xsd:complexContent> 
      <xsd:extension base="UiColumn"> 
        <xsd:attribute name="escape" type="xsd:boolean" use="optional" /> 
        <xsd:attribute name="isUrl" type="xsd:boolean" use="optional" />
        <xsd:attribute name="readOnly" type="xsd:boolean" use="optional" />
        <xsd:attribute name="required" type="xsd:boolean" use="optional" /> 
        <xsd:attribute name="renderedForView" type="xsd:boolean" use="optional" />
        <xsd:attribute name="rolesAllowedToEdit" type="xsd:boolean" use="optional" />
        <xsd:attribute name="validator" type="xsd:string" use="optional" />
        <xsd:attribute name="wbrChars" type="xsd:string" use="optional" />
      </xsd:extension> 
    </xsd:complexContent> 
  </xsd:complexType>  
  
  <xsd:complexType name="UiChart">
    <xsd:attribute name="id" type="xsd:string" use="required" />
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="model" type="xsd:string" use="required" />
    <xsd:attribute name="filter" type="xsd:string" use="optional" />
  </xsd:complexType>
  
</xsd:schema>

=== CenturyLinkCloud/mdw/mdw-hub/src/META-INF/mdw/mdw-hub-view.xml
<?xml version="1.0"?>
<view
  xmlns="http://mdw.centurylink.com/task"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://mdw.centurylink.com/task http://cshare.ad.qintra.com/sites/MDW/Developer%20Resources/Environment/schemas/Development/Task/TaskView_v03.xsd"
  skin="blueSky">

  <list
    id="userTaskList"
    name="My Tasks"
    model="com.centurylink.mdw.hub.ui.task.UserTasks"
    controller="com.centurylink.mdw.hub.ui.task.TaskListController"
    defaultSortColumn="instanceId"
    displayRows="25"
    allRowsLink="true"
    groupingOptions="name=Task Name,dueDate,orderId=Order,advisory"
    showTimings="false">
    <column
      attribute="selected"
      name=""
      checkbox="true" />
    <column
      attribute="instanceId"
      name="Task ID"
      linkAction="taskDetail"
      linkCondition="#{item.advisory != 'Invalid'}" />
    <column
      attribute="categoryCode"
      name="Category" />
    <column
      attribute="name"
      name="Name" />
    <column
      attribute="orderId"
      name="Order ID"
      linkAction="orderDetail"
      linkCondition="#{item.orderId != null}" />
    <column
      attribute="#{item.ownerType == 'EXTERNAL' ? 'External' : item.processInstanceId}" 
      name="Process"
      linkAction="processDetail" 
      linkCondition="#{item.ownerType != 'EXTERNAL'}" />
    <column
      attribute="status"    
      name="Status" />
    <column
      attribute="startDate"    
      name="Start Date"
      dateFormat="MMM dd, yyyy hh:mm aa" />
    <column
      attribute="dueDate"    
      name="Due Date"
      dateFormat="MMM dd, yyyy" />
    <column
      attribute="advisory"
      name="Advisory"
      styleClass="mdw_advisoryItem" />
  </list>
  
  <list
    id="workgroupTaskList"
    name="All Tasks"
    model="com.centurylink.mdw.hub.ui.task.WorkgroupTasks"
    controller="com.centurylink.mdw.hub.ui.task.TaskListController"
    defaultSortColumn="instanceId"
    paginatedResponse="true"
    exportable="true"
    allRowsLink="true"
    displayRows="25"
    pageSizeOptions="25,50,100,200"
    groupingOptions="name=Task Name,assigneeName,dueDate,orderId=Order,advisory"
    customButtons="createTask,Create Task,add.gif,go_createTask"    
    showTimings="false"
    columnarFilters="true"
    searchable="true"
    filter="workgroupTasksFilter"
    maxShowAllRows="500">
    <column
      attribute="selected"
      name=""
      checkbox="true" />
    <column
      attribute="instanceId"
      name="Task ID"
      linkAction="taskDetail"
      linkCondition="#{item.advisory != 'Invalid'}"
      filterField="instanceId" />
    <column
      attribute="categoryCode"
      name="Category"
      filterField="categoryId" />
    <column
      attribute="name"
      name="Name"
      filterField="name" />
    <column
      attribute="orderId"
      name="Order ID"
      linkAction="orderDetail"
      linkCondition="#{item.orderId != null}"
      filterField="masterRequestId" />
    <column
      attribute="#{item.ownerType == 'EXTERNAL' ? 'External' : item.processInstanceId}"
      name="Process"
      linkAction="processDetail"
      linkCondition="#{item.ownerType != 'EXTERNAL'}" />      
    <column
      attribute="status"
      name="Status"
      filterField="status" />
    <column
      attribute="startDate"    
      name="Start Date"
      dateFormat="MMM dd, yyyy hh:mm aa" />      
    <column
      attribute="assigneeName"
      name="Assignee"
      filterField="assignee" />
    <column
      attribute="dueDate"
      name="Due Date"
      dateFormat="MMM dd, yyyy"
      filterField="dueDate" />
    <column
      attribute="advisory"
      name="Advisory"
      styleClass="mdw_advisoryItem"
      filterField="advisory" />
      
    <!-- illustrates Task Indices syntax -->    
    <!-- 
    Syntax :
    <column
      attribute="#indiceskey"    
      name="DisplayName"
      filterField="filterAttribute" />    
    Example:
    <column
      attribute="#orderIdKey"    
      name="Order"
      filterField="#orderIdKey" />     
       -->
    <!-- illustrates process variables syntax ($-prefixed)-->   
    <!-- 
    Syntax :
    <column
      attribute="$processVariableName"    
      name="DisplayName"
      filterField="filterAttribute" />
    <column
      attribute="$userName"    
      name="User Name" 
      filterField="$userName"/>
     -->      
  </list>

  <filter
    id="workgroupTasksFilter"
    name="Filters"
    model="com.centurylink.mdw.taskmgr.ui.tasks.filter.TaskFilter"
    width="160px">
    <!--  columnar filters for process variables and for task indices   -->
   <!--   
   <field
      attribute="$userName"
      name="User Name"  
      modelType="java.lang.String"
      type="textInput" />
    <field
      attribute="#orderIdKey"
      name="Order Num"
      modelType="java.lang.String"
      type="textInput" /> -->
    <field
      attribute="instanceId"
      name="Task ID"
      modelAttribute="id"
      modelType="java.lang.Long"
      type="digitInput" />
    <field
      attribute="name"
      name="Task Name"
      modelAttribute="taskName"
      modelType="java.lang.String"
      type="selectInput"      
      lister="com.centurylink.mdw.taskmgr.ui.tasks.TaskNames" />
    <field
      attribute="categoryId"
      name="Category"
      modelAttribute="categoryId"
      modelType="java.lang.Integer"
      type="selectInput"
      lister="com.centurylink.mdw.taskmgr.ui.tasks.TaskCategories" />
    <field
      attribute="masterRequestId"
      name="Order ID"
      modelAttribute="orderId"
      modelType="java.lang.String"
      type="textInput" />
    <field
      attribute="status"
      name="Status"
      modelAttribute="statusCode"
      modelType="java.lang.Integer"
      defaultValue="-1"
      type="selectInput"
      lister="com.centurylink.mdw.taskmgr.ui.tasks.TaskStatuses" />
    <field
      attribute="advisory"
      name="Advisory"
      modelAttribute="stateCode"
      modelType="java.lang.Long"
      defaultValue="-1"
      type="selectInput"
      lister="com.centurylink.mdw.taskmgr.ui.tasks.TaskAdvisories" />
    <field
      attribute="dueDate"
      name="Due Date Range"
      modelType="java.util.Date"
      modelAttribute="estimatedCompletionDate"
      type="dateRange" />
    <field
      attribute="assignee"
      name="Assignee"
      modelAttribute="taskClaimUserId"
      modelType="java.lang.Long"
      type="selectInput"
      lister="com.centurylink.mdw.taskmgr.ui.user.Users" />
  </filter>

  <list
    id="taskNotes"
    name="Task Notes"
    model="com.centurylink.mdw.taskmgr.ui.tasks.notes.TaskNotes"
    controller="com.centurylink.mdw.taskmgr.ui.tasks.notes.TaskNotesActionController"
    defaultSortColumn="Modified Date"
    defaultSortDescending="true"
    displayRows="0">
    <column
      attribute="summary"
      name="Summary"
      expandable="true"
      expandedContent="/components/noteContent.xhtml"
      styleClass="mdw_noteColumn" />
    <column
      attribute="modifiedBy"
      name="Modified By" />
    <column
      attribute="modifiedDate"
      name="Modified Date"
      dateFormat="MMM dd, yyyy hh:mm aa" />
    <column
      attribute="'Edit'"
      name=""
      linkAction="editNote"
      image="/images/edit.gif" />
    <column
      attribute="'Delete'"
      name=""
      linkAction="deleteNote"
      image="/images/delete.gif" />
  </list>

  <list
    id="taskAttachments"
    name="Task Attachments"
    model="com.centurylink.mdw.taskmgr.ui.tasks.attachments.TaskAttachments"
    controller="com.centurylink.mdw.taskmgr.ui.tasks.attachments.TaskAttachmentsActionController"
    defaultSortColumn="Modified Date"
    defaultSortDescending="true"
    displayRows="0">
    <column
      attribute="name"
      name="File Name"
      linkAction="/servlet/AttachmentDownloadServlet?attachmentId=#{item.id}&amp;masterRequestId=#{item.masterRequestId}&amp;ownerId=#{item.ownerId}&amp;owner=#{item.owner}&amp;fileName=#{item.name}" />
    <column
      attribute="modifiedBy"
      name="Modified By" />
    <column
      attribute="modifiedDate"
      name="Modified Date"
      dateFormat="MMM dd, yyyy hh:mm aa" />
    <column
      attribute="'Delete'"
      name=""
      linkAction="deleteAttachment"
      image="/images/delete.gif" />
  </list>
  
  <list
    id="orderNotes"
    name="Order Notes"
    model="com.centurylink.mdw.taskmgr.ui.orders.notes.OrderNotes"
    controller="com.centurylink.mdw.taskmgr.ui.orders.notes.OrderNotesActionController"
    defaultSortColumn="Modified Date"
    defaultSortDescending="true"
    displayRows="15"
    allRowsLink="true">
    <column
      attribute="summary"
      name="Summary"
      expandable="true"
      expandedContent="/components/noteContent.xhtml"
      styleClass="mdw_noteColumn" />
    <column
      attribute="modifiedBy"
      name="Modified By" />
    <column
      attribute="modifiedDate"
      name="Modified Date"
      dateFormat="MMM dd, yyyy hh:mm aa" />
    <column
      attribute="'Edit'"
      name=""
      linkAction="editNote"
      image="/images/edit.gif" />
    <column
      attribute="'Delete'"
      name=""
      linkAction="deleteNote"
      image="/images/delete.gif" />
  </list>
  
  <list
    id="orderAttachments"
    name="Order Attachments"
    model="com.centurylink.mdw.taskmgr.ui.orders.attachments.OrderAttachments"
    controller="com.centurylink.mdw.taskmgr.ui.orders.attachments.OrderAttachmentsActionController"
    defaultSortColumn="Modified Date"
    defaultSortDescending="true"
    displayRows="15"
    allRowsLink="true">
    <column
      attribute="name"
      name="File Name"
      linkAction="/servlet/AttachmentDownloadServlet?attachmentId=#{item.id}&amp;masterRequestId=#{item.masterRequestId}&amp;ownerId=#{item.ownerId}&amp;owner=#{item.owner}&amp;fileName=#{item.name}&amp;contentType=#{item.contentType}" />
    <column
      attribute="modifiedBy"
      name="Modified By" />
