=== CenturyLinkCloud/mdw/mdw/classes/schemaorg_apache_xmlbeans/src/Workflow/ConfigManager.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://mdw.centurylink.com/workflow" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified" 
    targetNamespace="http://mdw.centurylink.com/workflow">

  <xsd:element name="ConfigManagerProjects">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" name="WorkflowApp" type="WorkflowApplication"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ConfigManager">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" minOccurs="0" name="Interface" type="Interface"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:complexType name="Interface">
    <xsd:sequence>
      <xsd:element name="EndPoint" type="InterfaceEndpoint"/>
      <xsd:element name="RequestXsdUrl" type="xsd:string" minOccurs="0"/>
      <xsd:element name="ResponseXsdUrl" type="xsd:string" minOccurs="0"/>
      <xsd:element name="Process" type="xsd:string" minOccurs="0"/>
      <xsd:element name="Activity" type="xsd:string" minOccurs="0"/>
      <xsd:element name="Adapter" type="xsd:string" minOccurs="0"/>
      <xsd:element name="ExternalEvent" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="protocol" type="xsd:string" use="required"/>
    <xsd:attribute name="direction" type="InterfaceDirection" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="InterfaceInstance">
    <xsd:sequence>
      <xsd:element name="EndPointValue" type="xsd:string"/>
      <xsd:element name="Topic" type="xsd:string" minOccurs="0"/>
      <xsd:element name="StubMode" type="xsd:boolean" default="false"/>
      <xsd:element name="StubXml" type="xsd:string" minOccurs="0"/>
      <xsd:element name="LogRequest" type="xsd:boolean" default="true"/>
      <xsd:element name="LogResponse" type="xsd:boolean" default="true"/>
      <xsd:element name="ValidateRequest" type="xsd:boolean" default="false"/>
      <xsd:element name="ValidateResponse" type="xsd:boolean" default="false"/>
    </xsd:sequence>
    <xsd:attribute name="interfaceName" type="xsd:string" use="required"/>
  </xsd:complexType>
  
  <xsd:simpleType name="InterfaceDirection">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="IN"/>
      <xsd:enumeration value="OUT"/>
    </xsd:restriction>
  </xsd:simpleType>
    
  <xsd:complexType name="InterfaceEndpoint">
    <xsd:attribute name="group" type="xsd:string" use="optional"/>
    <xsd:attribute name="property" type="xsd:string" use="optional"/>
    <xsd:attribute name="responder" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="WorkflowApplication">
    <xsd:sequence>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Url" type="WorkflowUrl"/>
      <xsd:element minOccurs="0" name="Repository" type="VcsRepository" />
      <xsd:element maxOccurs="unbounded" name="Environment" type="WorkflowEnvironment"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="malAppName" type="xsd:string" use="optional"/>
    <xsd:attribute name="appName" type="xsd:string" use="optional"/>
    <xsd:attribute name="ecomAcronym" type="xsd:string" use="optional"/>
    <xsd:attribute name="acronym" type="xsd:string" use="optional"/>
    <xsd:attribute name="webContextRoot" type="xsd:string" use="optional"/>
    <!-- specify the following if services have a separate context root from web -->
    <!-- will also be used for apps where only some envs are upgraded -->
    <xsd:attribute name="servicesContextRoot" type="xsd:string" use="optional"/>
    <!-- the following two entries are not needed for MDW 4.x+ apps since they will be autodiscovered -->
    <xsd:attribute name="designerContextRoot" type="xsd:string" use="optional"/>
    <xsd:attribute name="taskManagerContextRoot" type="xsd:string" use="optional"/>
    <!-- config manager apps which should be accessible for BAM reporting -->
    <xsd:attribute name="bamRelatedApps" type="xsd:string" use="optional"/>
  </xsd:complexType>
  
  <xsd:complexType name="WorkflowEnvironment">
    <xsd:sequence>
      <xsd:element maxOccurs="unbounded" name="ManagedServer" type="ManagedNode"/>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="Url" type="WorkflowUrl"/>
      <xsd:element minOccurs="0" name="EnvironmentDb" type="EnvironmentDB"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="owner" type="xsd:string" use="required"/>
    <xsd:attribute name="envSuffix" type="xsd:string" use="optional"/>
  </xsd:complexType>
  
  <xsd:complexType name="WorkflowUrl">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="label" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>  
  </xsd:complexType>

  <xsd:complexType name="VcsRepository">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="provider" type="xsd:string" use="required"/>
        <xsd:attribute name="url" type="xsd:string" use="optional"/>
        <xsd:attribute name="localPath" type="xsd:string" use="optional"/>
        <xsd:attribute name="user" type="xsd:string" use="optional"/>
        <xsd:attribute name="password" type="xsd:string" use="optional"/>
      </xsd:extension>
    </xsd:simpleContent>  
  </xsd:complexType>

  <xsd:complexType name="EnvironmentDB">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="jdbcUrl" type="xsd:string" use="required"/>
        <xsd:attribute name="user" type="xsd:string" use="required"/>
        <xsd:attribute name="password" type="xsd:string" use="required"/>
        <xsd:attribute name="schemaOwner" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>  
  </xsd:complexType>

  <xsd:complexType name="ManagedNode">
    <xsd:attribute name="host" type="xsd:string" use="required"/>
    <xsd:attribute name="port" type="xsd:integer" use="required"/>
    <xsd:attribute name="webRoot" type="xsd:string" use="optional"/>
  </xsd:complexType>
  
  <xsd:element name="BusConnector">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="BusTopic" type="BusTopic"/>
        <xsd:element name="BusProcessor" type="BusProcessor"/>
        <xsd:element name="Attribute" type="BusAttribute"/>
      </xsd:choice>
    </xsd:complexType>  
  </xsd:element>
  
  <xsd:complexType name="BusTopic">
    <xsd:sequence>
      <xsd:element name="Attribute" type="BusAttribute" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="class" type="xsd:string" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="BusProcessor">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="Attribute" type="BusAttribute" />
      <xsd:element name="BusPolicy" type="BusPolicy" />
    </xsd:choice>  
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="class" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="BusPolicy">
    <xsd:sequence>
      <xsd:element name="Attribute" type="BusAttribute" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>  
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="BusAttribute" mixed="true">
    <xsd:sequence>
      <xsd:element name="entry" type="BusEntry" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>  
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="BusEntry">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="type" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:simpleContent> 
  </xsd:complexType>
  
</xsd:schema>

=== CenturyLinkCloud/mdw/mdw-hub/web/Discovery/ConfigManagerProjects.xml
<ConfigManagerProjects
  xmlns="http://mdw.centurylink.com/workflow"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://mdw.centurylink.com/workflow ../../mdw-schemas/schemas/Workflow/ConfigManager.xsd">
  
  <WorkflowApp
    name="ACE-VOIP"
    malAppName="ACE-VOIP"
    ecomAcronym="ace-voip" 
    webContextRoot="MDWWeb"
    designerContextRoot="MDWDesignerWeb"
    taskManagerContextRoot="MDWTaskManagerWeb">
    <Url id="sharePointSiteUrl" label="SharePoint Site">http://cshare.ad.qintra.com/sites/mdw</Url>
    <Url id="anthill3Url" label="5.2 Anthill">http://lxdenvmtc143.dev.qintra.com:7209/anthill</Url>
    <Url id="archivaRepo" label="MDW Archiva Maven Repo">http://archiva.corp.intranet/archiva/repository/mdw</Url>
    <Url id="mdwJavaDocs" label="MDW 5.2 JavaDocs">http://lxdenvmtc143.dev.qintra.com:7021/MDWWeb/javadoc/index.html</Url>
      <Url id="discussionBoard" label="MDW Discussion Board">http://cshare/sites/MDW/Lists/MDW%20Support</Url> 
    <Environment name="Dev 1" owner="Greg Walters">
      <ManagedServer host="lxomavmtc205.dev.qintra.com" port="10028" />
      <Url id="userAccessBaseUrl" label="User Access">http://lxomavmtc205.dev.qintra.com:10028</Url>
      <Url id="consoleUrl" label="Karaf Shell">ssh://lxomavmtc205.dev.qintra.com:8128</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@lxomavdora027.dev.qintra.com:1550:avoip01d" user="acevoip_app" password="BxfuA/xZ55+qKw8V8NcfcaorDxXw1x9x" />
    </Environment>
    <Environment name="Test 1" owner="Greg Walters">
      <ManagedServer host="acevoipsmx.test.intranet" port="10001" />
      <Url id="userAccessBaseUrl" label="User Access">http://acevoipsmx.test.intranet:10001</Url>
      <Url id="consoleUrl" label="Karaf Shell">ssh://acevoipsmx.test.intranet:20001</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@avoip01tdb.dev.qintra.com:1551:avoip01t" user="acevoip_app" password="BxfuA/xZ55+qKw8V8NcfcaorDxXw1x9x" />
    </Environment>
    <Environment name="Test 2" owner="Greg Walters">
      <ManagedServer host="acevoipsmx.test.intranet" port="10002" />
      <Url id="userAccessBaseUrl" label="User Access">http://acevoipsmx.test.intranet:10002</Url>
      <Url id="consoleUrl" label="Karaf Shell">ssh://acevoipsmx.test.intranet:20002</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@avoip02tdb.dev.qintra.com:1550:avoip02t" user="acevoip_app" password="BxfuA/xZ55+qKw8V8NcfcaorDxXw1x9x" />
    </Environment>
    <Environment name="Test3" owner="Shannon Shen">
      <ManagedServer host="acevoipsmx.test.intranet" port="10004" />
      <Url id="userAccessBaseUrl" label="User Access">http://acevoipsmx.test.intranet</Url>
      <Url id="consoleUrl" label="Karaf Shell">ssh://acevoipsmx.test.intranet</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@avoip03tdb.dev.qintra.com:1553:avoip03t" user="ACEVOIP_APP" password="6Az9R3oA4O6qKw8V8NcfcaorDxXw1x9x" />
    </Environment>
    <Environment name="E2E" owner="Greg Walters">
      <ManagedServer host="acevoipsmx.test.intranet" port="10003" />
      <Url id="userAccessBaseUrl" label="User Access">http://acevoipsmx.test.intranet:10003</Url>
    <Url id="consoleUrl" label="Karaf Shell">ssh://acevoipsmx.test.intranet:10003</Url>
    <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@avoipe2e_db.dev.qintra.com:1567:avoipe2e" user="ACEVOIP_APP" password="6Az9R3oA4O6qKw8V8NcfcaorDxXw1x9x" />
  </Environment>
    <Environment name="Production" owner="Greg Walters">
      <ManagedServer host="acevoipsmx.corp.intranet" port="80" />
      <Url id="userAccessBaseUrl" label="User Access">http://acevoipsmx.corp.intranet</Url>
      <Url id="consoleUrl" label="Karaf Shell">ssh://acevoipsmx.corp.intranet</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@avoip01pdb.qintra.com:1534:avoip01p" user="ACEVOIP_APP" password="T2+fJFo0evLmJq+raEf/P6orDxXw1x9x" />
    </Environment>
  </WorkflowApp> 

  <WorkflowApp
    name="BVoIP Workflow"
    malAppName="BUSINESS VOIP WORKFLOW"
    ecomAcronym="bvoipwf"
    webContextRoot="BVoIPWorkflowWeb"
    designerContextRoot="BVoIPWorkflowDesignerWeb"
    taskManagerContextRoot="BVoIPWorkflowTaskManager">
    <Url id="anthillUrl" label="Anthill">http://lxdnd54c.dev.qintra.com:7001/anthill</Url>
    <Environment name="Integration" owner="vairi">
      <ManagedServer host="qtomavmdt107.dev.qintra.com" port="7001" />
      <Url id="userAccessBaseUrl" label="User Access">http://qtomavmdt107.dev.qintra.com:7001</Url>
      <Url id="consoleUrl" label="WebLogic Console">http://qtomavmdt107.dev.qintra.com:7001/console</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@vomwfdevdb.dev.qintra.com:1593:vomwfdev" user="bvoip_app" password="bFMVPhTOOyUDvksY1abga2ucUZh8e4aq" schemaOwner="BVOIP_MDW"/>      
    </Environment>
    <Environment name="System Test 1" owner="vairi">
      <ManagedServer host="ecomt180.dev.qintra.com" port="7329" />
      <ManagedServer host="ecomt181.dev.qintra.com" port="7329" />
      <Url id="userAccessBaseUrl" label="User Access">https://ecomt-v1.dev.qintra.com</Url>
      <Url id="consoleUrl" label="WebLogic Console">http://ecomt182.dev.qintra.com:9329/console</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@suomt102.qwest.net:1528:vomwfst1" user="bvoip_app" password="bFMVPhTOOyU9coaMXxqjJWEndqnwppz+" schemaOwner="BVOIP_MDW"/>
    </Environment>
    <Environment name="System Test 2" owner="lsingh">
      <ManagedServer host="ecomt180.dev.qintra.com" port="7359" />
      <ManagedServer host="ecomt181.dev.qintra.com" port="7359" />
      <Url id="userAccessBaseUrl" label="User Access">https://bvoipwf-test2.dev.qintra.com</Url>
      <Url id="consoleUrl" label="WebLogic Console">http://ecomt182.dev.qintra.com:9359/console</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@vomwfst2db.dev.qintra.com:1603:vomwfst2" user=" bvoip_app" password="bFMVPhTOOyU9coaMXxqjJbDQjLrtda46" schemaOwner="BVOIP_MDW"/>
    </Environment>  
    <Environment name="End-To-End" owner="vairi">
      <ManagedServer host="ecomt180.dev.qintra.com" port="7539" />
      <ManagedServer host="ecomt181.dev.qintra.com" port="7539" />
      <Url id="userAccessBaseUrl" label="User Access">https://ecomt-v3.dev.qintra.com</Url>
      <Url id="consoleUrl" label="WebLogic Console">http://ecomt157.dev.qintra.com:9367/console</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@151.117.14.115:1549:vomwfe2e" user="bvoip_app" password="bFMVPhTOOyVD3nFn5pfQEGFGZp4EPaEg" schemaOwner="BVOIP_MDW"/>
    </Environment>  
    <Environment name="Production" owner="vairi">
      <ManagedServer host="ecom-ne174.qintra.com" port="7177" />
      <ManagedServer host="ecom-ne175.qintra.com" port="7177" />
      <ManagedServer host="ecom-ne176.qintra.com" port="7177" />
      <Url id="userAccessBaseUrl" label="User Access">https://ecom-ne110.qintra.com:50656</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@vomwf01pdb.qintra.com:1522:vomwf01p" user="bvoip_app" password="bFMVPhTOOyVprZULawzZT6orDxXw1x9x" schemaOwner="BVOIP_MDW"/>
    </Environment>  
  </WorkflowApp>
  
  <WorkflowApp
    name="BVoIP Workflow Cloud"
    malAppName="BUSINESS VOIP WORKFLOW"
    ecomAcronym="bvoipwf">
    <Repository provider="Git" />
    <Environment name="Dev Int" owner="Pradeep Rajashekar">
      <ManagedServer host="ne1itcdrhfuse06.dev.intranet" port="8001" webRoot="MDWHub" />
      <Url id="consoleUrl" label="Karaf Shell">ssh://%MDW_CLOUD_USER%@ne1itcdrhfuse06.dev.intranet:10001</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@NE1ITCDRHDB34.ne1.savvis.net:1523:vomwfint" user="bvoip_app" password="bFMVPhTOOyUDvksY1abga2ucUZh8e4aq" />   
    </Environment>
    <Environment name="Test 2" owner="Naveena Bellamkonda">
      <ManagedServer host="ne1itctrhfuse11.test.intranet" port="8076" webRoot="MDWHub" />
      <ManagedServer host="ne1itctrhfuse12.test.intranet" port="8076" webRoot="MDWHub" />
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@NE1ITCTRHDB43.ne1.savvis.net:1555:vomwfst2" user="VOIPWF_APP" password="JKwdVLuFdIyx1l9SHLjKeaorDxXw1x9x" />   
    </Environment>
    <Environment name="E2E" owner="Pradeep Rajashekar">
      <ManagedServer host="ne1itctrhfuse17.test.intranet" port="8078" webRoot="MDWHub" />
      <ManagedServer host="ne1itctrhfuse18.test.intranet" port="8078" webRoot="MDWHub" />
      <Url id="consoleUrl" label="Karaf Shell">ssh://%MDW_CLOUD_USER%@ne1itctrhfuse17.test.intranet:10078</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@NE1ITCTRHDB44.ne1.savvis.net:1545:vomwfe2e" user="bvoip_app" password="bFMVPhTOOyVD3nFn5pfQEGFGZp4EPaEg" />   
    </Environment>
  </WorkflowApp>

  <WorkflowApp
    name="Common Content WF"
    malAppName="COMMON CONTENT WORKFLOW"
    ecomAcronym="ccwf" 
    webContextRoot="CCCMDWWeb"
    servicesContextRoot="CCWFWeb"
    designerContextRoot="CCWFDesignerWeb"
    taskManagerContextRoot="CCWFTaskManagerWeb">
    <Url id="anthillUrl" label="Anthill">http://lxdnd54c.dev.qintra.com:7001/anthill</Url>    
    <Environment name="Integration" owner="pkhande">
      <ManagedServer host="lxdenvmtc145.dev.qintra.com" port="6061" />
      <Url id="userAccessBaseUrl" label="User Access">http://lxdenvmtc145.dev.qintra.com:6061</Url>
      <Url id="consoleUrl" label="WebLogic Console">http://lxdenvmtc145.dev.qintra.com:5061/console</Url>
      <EnvironmentDb jdbcUrl="jdbc:oracle:thin:@ccwfdevdb.dev.qintra.com:1670:ccwfdev" user="ccwf_app" password="g1Wi7Im5xpcw147LSVotGqorDxXw1x9x"/>  
    </Environment>
    <Environment name="System Test 1" owner="jrieck">
      <ManagedServer host="ecomt155.dev.qintra.com" port="7273" />
      <ManagedServer host="ecomt156.dev.qintra.com" port="7273" />
      <Url id="userAccessBaseUrl" label="User Access">https://ecomt-v1.dev.qintra.com</Url>
      <Url id="consoleUrl" label="WebLogic Console">http://ecomt165.dev.qintra.com:9273/console</Url>
